### ISSUE TITLE
书中243页也有问题

### ISSUE THREAD

**Issue by myd1** [dennycn/python_practice_of_data_analysis_and_mining#2]
书中243页也有问题，关于SQLAlchemy安装的问题，应该是先安装PyMySQL，再安装SQLAlchemy

**Comment by keefecn** [comment]
> 
> 
> 书中243页也有问题，关于SQLAlchemy安装的问题，应该是先安装PyMySQL，再安装SQLAlchemy

你说的是 engine = create_engine(
    'mysql+pymysql://root:123456@127.0.0.1:3306/test?charset=utf8')
这肯定需要pymysql的支持啊，不然就无法处理这个uri。
